### PR TITLE
Modernize forum

### PR DESCRIPTION
**Pull request by gajop**
I suggest we add an upvote system for the forum and a syntax highlight system for both the forum and wiki.  Related mantis feature requests: https://springrts.com/mantis/view.php?id=4992 and https://springrts.com/mantis/view.php?id=4994

I've already made the forum changes, but this should be done for the wiki :https://www.mediawiki.org/wiki/Extension:SyntaxHighlight_GeSHi . 

Before I attempt it, why are we using an old version of MediaWiki (1.19.24)? The new version already comes bundled with it so it would be good to upgrade it. Should we just do this?

### CODE REVIEW

**Comment by abma** [comment]
> Before I attempt it, why are we using an old version of MediaWiki (1.19.24)? The new version already comes bundled with it so it would be good to upgrade it. Should we just do this?

it wasn't upgraded because of https://springrts.com/phpbb/viewtopic.php?f=71&t=33481

when upgrading, please use the lts version which is 1.23.x atm.

**Comment by abma** [comment]
not upgraded means:

it was upgraded but not applied to the productive website because the layout broke, see http://test.springrts.com/wiki/Main_Page

**Comment by abma** [comment]
thanks!

**Comment by gajop** [comment]
Amazingly fast, thanks! I'll be away from my work PC for a few days I'd you
plan to deploy it on the test server soon. We may want to do some
modifications on it still I think.

**Comment by gajop** [comment]
The mediawiki issue may be non trivial. Is there any way to obtain the
springrts layout so I can play with it locally?

**Comment by abma** [comment]
> Amazingly fast, thanks! I'll be away from my work PC for a few days I'd you plan to deploy it on the test server soon. We may want to do some modifications on it still I think

the changes are already deployed at the test server...

> The mediawiki issue may be non trivial. Is there any way to obtain the springrts layout so I can play with it locally?

the old layout isn't compatible, so nothing to play. for the reference: https://github.com/spring/spring-website/blob/1f6caa1de092c74a10e8dd8eef4ad93086f0dab4/wwwroot/mediawiki/skins/SpringNew.php

i got stuck in setting up the bootstrap skin:

https://springrts.com/phpbb/viewtopic.php?f=71&t=33481&start=20#p571659

**Comment by Tarendai** [comment]
I would note that there is no trace of the roflcopter design on the test sites forum at the moment, the footer should be ammended

**Comment by gajop** [comment]
Oh, OK. I posted on the main forums to get some feedback.
I'm completely happy with ditching the old layout as long as nothing
breaks. It wasn't very modern and seemed as someone's personal MySpace page
:P

Amazingly fast, thanks! I'll be away from my work PC for a few days I'd you
plan to deploy it on the test server soon. We may want to do some
modifications on it still I think

the changes are already deployed at the test server...

The mediawiki issue may be non trivial. Is there any way to obtain the
springrts layout so I can play with it locally?

the old layout isn't compatible, so nothing to play. for the reference:
https://github.com/spring/spring-website/blob/1f6caa1de092c74a10e8dd8eef4ad93086f0dab4/wwwroot/mediawiki/skins/SpringNew.php

i got stuck in setting up the bootstrap skin:

https://springrts.com/phpbb/viewtopic.php?f=71&t=33481&start=20#p571659

—
Reply to this email directly or view it on GitHub
<https://github.com/spring/spring-website/pull/65#issuecomment-156104799>.

**Comment by ForbodingAngel** [comment]
I still contend that github should be used for the wiki. It is far batter than the mediawiki mess.

Wiki should not be shoehorned into the pre-2000 layout of the current spring site.

**Comment by gajop** [comment]
Upgrading makes sense but I'd still stick with the true and tried mediawiki
rather than experiment with github - it's quite likely limited and won't
integrate with forum's authentication/permission settings.

**Pull request merged**
