### PR TITLE
Flatten, Simplify, Escape, and Optimise

### PR DESCRIPTION
**Pull request by tomjn**
This PR makes a number of changes that should increase rendering time, simplify graphics, and make the frontpage look much cleaner when you look closer without changing the design

It also adds in several elements and class names that will be necessary for further improvements to the homepage

### CODE REVIEW

**Comment by abma** [comment]
wwwroot/mediawiki/ was changed, can you please revert these changes? (they will be overwritten next mediawiki update...)

**Comment by tomjn** [comment]
The changes appeared immediately after I did a `git clone`, they weren't made by me and I suspect it has something to do with case sensitivity and file systems. I do not know with certainty how they got there, and I was surprised to find any changes in the folder after doing a clean git clone into a new folder.

The only thing I could discern is that the modified files had differing case, and that until the issue was resolved, rebasing to bring my fork up to date with the main spring repository was not possible.

If you can advise on how I might resolve this?

**Comment by tomjn** [comment]
latest commit should undo the changes in ac59c36f32c3f6d521e095d25956cd9c5b506d84

**Comment by abma** [comment]
> that should increase rendering time

i hope you meant decrease?

**Comment by tomjn** [comment]
decrease*, it removes some excessive use of text shadow and translucent effects

**Comment by tomjn** [comment]
@abma any remaining issues?

**Comment by abma** [comment]
yes, time. sorry + thanks!

**Comment by abma** [comment]
FYI: https://github.com/spring/spring-website/commit/255d7ea85fa30de12b87306f47621d82a51c75d0

**Comment by abma** [comment]
is it by intention that the image is below the "buttons"?

see http://test.springrts.com/

**Comment by tomjn** [comment]
I've sent a follow up PR, as a sidenote, why is the server running PHP 5.5.9? The only supported version of PHP 5.* branch is the latest v5.6, otherwise we're recommended to move to 7.*, any security issues that arise in 5.5.9 won't get fixed.

We should be on v5.6.28 with automated updates to minor versions pending tests for PHP 7, we can run PHPCompat-Info if there are concerns the existing site won't work with v7

**Comment by abma** [comment]
http://packages.ubuntu.com/trusty/php5

afaik ubuntu/debian backports security patches

**Comment by tomjn** [comment]
hmmm interesting, although general bug and crash fixes aren't backported

**Pull request merged**
