### PR TITLE
Fix navbar on wiki

### PR DESCRIPTION
**Pull request by ForbodingAngel**
Wheeee.

Related to: https://github.com/spring/spring-website/pull/49

### CODE REVIEW

**Comment by abma** [comment]
better, but in wiki the font isn't aligned the same (bottom vs. center it seems).

**Comment by ForbodingAngel** [comment]
It isn't? It should be... Lemmie look again...

**Comment by ForbodingAngel** [comment]
No it is aligned, what you're seeing is the effect of the text underline, which I specifically removed... I'll add important to it. Ffs.

Someone feel free to tell me why phpbb has no less than ONE HUNDRED AND TWENTY font-size declarations... Christ, I wanna stab whoever develops that pile of crap with a rusty spoon.

Fix incoming, Abma.

**Comment by ForbodingAngel** [comment]
Wait, nm, if you do a ctrl + f5 (forced refresh), it will fix itself.

**Comment by ForbodingAngel** [comment]
https://github.com/spring/spring-website/pull/51

**Pull request merged**
