### PR TITLE
Raise font awesome import above everything else. Phpbb headers do some o...

### PR DESCRIPTION
**Pull request by ForbodingAngel**
...dd if statements using html comments that are breaking it

### CODE REVIEW

**Comment by ForbodingAngel** [comment]
NO, do not remove it! The spring theme is a child theme. Leave the parent alone -_-

**Comment by abma** [comment]
the REFERENCE(s) should be removed!!!

**Comment by abma** [comment]
in other words: don't change / touch prosilver! it will be overwritten very likely next update

**Comment by ForbodingAngel** [comment]
Yeah, you are correct. As mentioned in the other thread, I was not previously aware that phpbb supported child themes. I will split my changes into it's own stylesheet linked from the spring child theme and that should solve the issue entirely. I read up on how child themes work in phpbb earlier, and it's pretty much simple file replacements in the child theme. Very basic as far as I can tell.

I'll do it tomorrow when I can read straight, at the moment everything is blurry because I'm exhausted.

BTW fyi, the way your above comment reads, it reads like you were on the verge of removing the entire parent theme, hence my reaction. That would be bad.

**Pull request merged**
