### PR TITLE
Fix some missing endings in spring stylesheet

### PR DESCRIPTION
**Pull request by ForbodingAngel**
Remove overrides from prosilver and put them into child theme overrides.css

### CODE REVIEW

**Comment by ForbodingAngel** [comment]
"Make avatar, title, postcount better lined up on mobile"

Before: http://i.imgur.com/I7bmo0O.png
After: http://i.imgur.com/NsSJ8rN.png

**Comment by ForbodingAngel** [comment]
Sexy image containers: http://i.imgur.com/iUFGP7l.png
Border to poster information: http://i.imgur.com/SmE2Pld.png

**Comment by abma** [comment]
thanks a lot for moving it to the spring theme!

**Comment by ForbodingAngel** [comment]
Thanks for bringing it to my attention that we were using a child theme. When you changed the comment in overall header, that's when I realized what was going on and it explained why the spring theme was so bare bones.

**Pull request merged**
