### PR TITLE
Put the Avatars on the left

### PR DESCRIPTION
**Pull request by Tarendai**
Avatars are on the right, put them on the left

### CODE REVIEW

**Comment by ForbodingAngel** [comment]
Changes like this should be made in overrides.css, not spring.css. Trivial complaint.

Avatars are better on the right. Makes far more sense as hotspots for reading are on the left side. Therefore, by having avatar panels on the right side, we get less important information out of the way, and put content first.

Unless the argument is that the avatar sidebar is more important than the post content, in which case, that would be ridiculous.

**Comment by abma** [comment]
no

**Comment by Tarendai** [comment]
I actually like them on the right, this was more to show people that they
were wasting their time arguing about it and should just make a pull
request if it bothered them so much

**Comment by ForbodingAngel** [comment]
@Tarendai , yeah I figured as much :-)

If someone complains about something and hasn't submitted a pull request in over a week when I have provided the relevant code on a silver platter, it's hard to take the complaint seriously.

**Pull request closed without merging**
