### PR TITLE
update front page news css

### PR DESCRIPTION
**Pull request by springraaar**
update front page news css with improved header highlight and content separation

### CODE REVIEW

**Comment by springraaar** [comment]
image

**Comment by tomjn** [comment]
@springraaar margins would be better for defining hierarchy here, but at the moment there's a bug where the second news item contains the 3rd/4th/etc items inside it that makes proper styling a bit difficult

**Comment by tomjn** [comment]
Looks like it doesn't balance unclosed tags and the latest post by Abma has `[code]` bbtags that aren't processed correctly

**Comment by tomjn** [comment]
With the following changes this would be possible:

Suggestions:

 - remove the background and border radius on the main content wrapper
 - move the border radius and the box shadow to each sub-section
 - apply it to each news item and give it a bottom margin of 1em
 - change the news headings so that they're actual headings with `h3` tags not `div`
 - give the news headings a top/bottom margin of 0
 - make the about tag have a top padding/margin of 0
 - bump the top/bottom padding of news items to 20px but keep the left/right at 8px 

Screenshot 2022-05-30 at 22 28 03

**Comment by springraaar** [comment]
> @springraaar margins would be better for defining hierarchy here, but at the moment there's a bug where the second news item contains the 3rd/4th/etc items inside it that makes proper styling a bit difficult

yes i know,  i used the html editor on the ctrl-shift-i inspector on firefox to edit the html before doing the printscreen to put move those news items to the parent element.

The processing of the msg text creates invalid html which breaks the page layout:

:<CODE><div class="codebox">Unattended-Upgrade::Automatic-Reboot "true";Unattended-Upgrade::Automatic-Reboot-Time "10:00";[/code]</CODE>

(that codebox div isn't closed properly)

A lazy fix for that would be editing the corresponding post or fixing the msg text on the database directly. A less lazy fix would probably imply using something like this
https://www.php.net/manual/en/tidy.repairstring.php

on
https://github.com/spring/spring-website/blob/master/wwwroot/includes/news.php#L50

(although that might make the page take longer to load, atm the html is generated in about 70ms)

**Comment by springraaar** [comment]
As for the style, i prefer my suggestion but your kind of separator is fine too, i don't have a strong opinion on this.

**Comment by tomjn** [comment]
@springraaar check my other PR's they should fix the issue and some other things

**Comment by springraaar** [comment]
there's no pr with the style changes you suggested, perhaps you could add them to this PR : https://github.com/spring/spring-website/pull/84

**Comment by tomjn** [comment]
I'd rather implement smaller fixes for now, else I'd need to setup a local environment. I've plenty of ideas but don't want to get carried away when there are bugs to fix

**Comment by abma** [comment]
thank you!

**Pull request merged**
