### PR TITLE
Dump the spring banner when not on the main site, replace with navbar

### PR DESCRIPTION
**Pull request by ForbodingAngel**
This bar would only happen when you were not on the main site. Like if you were on the forums, wiki or mantis, you would get this nav bar that helps you navigate the entire site at any time.

Looks like this: http://i.imgur.com/Dj3PLyl.png

(Without the home and download icons btw)

### CODE REVIEW

**Comment by ForbodingAngel** [comment]
What happens when you scroll down: http://i.imgur.com/a498lpy.png

**Comment by gajop** [comment]
Looks good. Does it appear inconsistent with the site?
Will the mantis also have these links? I always thought it was rather bad
not to have any there.

**Comment by ForbodingAngel** [comment]
Well this only covers the forum currently. I figured we could get it in one spot the way we want it, then port it to everywhere else. It should be notice that the way I did this, it's a matter of editing 2 lines to change it back to the way it was.

So to answer your question, yes it will be consistent, however, it would be best to get the navbar finalized before porting it to mantis/wiki. Hopefully that makes sense.

That said ideally, we can just call that header and style file everywhere else on the site. It would be silly and crappy dev to have multiple copies of it (and I'd QQ muchly).

**Comment by ForbodingAngel** [comment]
Umm abma don't merge this yet. I'mma try to go ahead and apply it to the wiki and mantis. It's all a header template file so it's not like it's a big deal.

**Comment by gajop** [comment]
What's the reason you can't just use it everywhere, including the site?
Isn't this just a change in the banner?

2015-06-03 14:30 GMT+09:00 ForbodingAngel <notifications@github.com>:

**Comment by ForbodingAngel** [comment]
Displaying it on the site itself needs some debate imo. The original idea was to display this everywhere that isn't the mainsite. And the mainsite would have the banners.

**Comment by ForbodingAngel** [comment]
Ok added to the wiki. Now to add this to mantis... heh this'll be interesting.

**Comment by ForbodingAngel** [comment]
Actually, mantis is a different animal, you can merge this if you like and we can go ahead about the business of figuring out what changes are needed for the navbar.

**Comment by gajop** [comment]
That's what I thought as well, but it seems AF managed to do something. Was
that just by hacking the outputted HTML in chrome?

2015-06-03 14:46 GMT+09:00 ForbodingAngel <notifications@github.com>:

**Comment by ForbodingAngel** [comment]
Yes. In fact that's usually how I do most everything (except I do things in css which is waaaay different).

But mantis is a bit of a clusterfuck. I found where I can jack in the header content cleanly, but I'mma have to do a bit of css magic special just for mantis so that it all plays nicely.

Mantis has always been a bit of an outlier, so if it doesn't get the bar right away that won't be any huge deal.

**Comment by Tarendai** [comment]
My embed code should just work anywhere, so long as you can sneak the snippet in somewhere, but I agree, Mantis is a bit of a mess, it's not something that has a theming system

The homepage and the media page are what I'd count as the main site as they're not a part of any other CMS or software, but if you guys are happy for the new nav bar to appear there then go ahead

I've some suggestions design-wise which I'll make once this is live as I consider this PR an improvement

**Comment by Tarendai** [comment]
Of note, https://github.com/mantisbt-plugins/google-analytics/blob/master/GoogleAnalytics/GoogleAnalytics.php

**Comment by Tarendai** [comment]
image

**Comment by ForbodingAngel** [comment]
Yeah I was considering that. I'll switch it up real quick.

**Comment by abma** [comment]
will apply on test site only and wait a bit for feedback.

**Comment by abma** [comment]
looks weird on the wiki, i.e

http://test.springrts.com/wiki/Games

**Comment by ForbodingAngel** [comment]
It's because of spring style orgy that I've been trying to fix (mostly to blame is phpbb). I'll fix it, thanks for the heads up.

**Comment by ForbodingAngel** [comment]
New pull request: https://github.com/spring/spring-website/pull/50

**Comment by Tim-Blokdijk** [comment]
It's a better design then the existing header. Feel free to drop the footer.

**Pull request merged**
