### PR TITLE
Make pagination more obvious, fix typos.

### PR DESCRIPTION
**Pull request by ForbodingAngel**
Easier to see what page you're on: http://i.imgur.com/fhQKGyR.png

### CODE REVIEW

**Comment by ForbodingAngel** [comment]
Augh I pushed the changes to my fork before the merge happened... Arugh EFF U GIT.

Sorry Abma.

**Comment by ForbodingAngel** [comment]
Less lolhueg pagination: http://i.imgur.com/EX2UptG.png

**Comment by abma** [comment]
AWWW, again you've downgraded the submodule, please fix that first!

**Comment by abma** [comment]
very likely you have to run:
git submodule sync
git submodule update
git submodule foreach git checkout master

**Comment by ForbodingAngel** [comment]
Thanks abma, this was the output:
Forboding Angel@FORBODING-DESK ~/Documents/GitHub/spring-website (master)
$ git submodule sync
Synchronizing submodule url for 'source-integration'

Forboding Angel@FORBODING-DESK ~/Documents/GitHub/spring-website (master)
$ git submodule update

Forboding Angel@FORBODING-DESK ~/Documents/GitHub/spring-website (master)
$ git submodule foreach git cheackout master
Entering 'source-integration'
git: 'cheackout' is not a git command. See 'git --help'.

Did you mean this?
        checkout
Stopping at 'source-integration'; script returned non-zero status.

So yeah, basically it all worked fine up to the last command.

**Comment by ForbodingAngel** [comment]
Ok... updated correctly now?

**Comment by abma** [comment]
no, the commit is still old, this should fix it:
git submodule foreach git pull

then the submodule should have 6f2bc1307186ebbd86d30b91852449fb72e8dccb checked out.

(no clue how it happened)

**Comment by abma** [comment]
in other words, its correct when "source-integration" doesn't show up in the diff any more...

**Comment by ForbodingAngel** [comment]
Ok done

**Pull request merged**
